const vscode = require('vscode');
const axios = require('axios').default;

/**
 * @param {vscode.ExtensionContext} context
 */

vscode.workspace.onDidChangeTextDocument(event => {
    if (event.contentChanges.some(change => change.text === '    ')) {
		codeSuggest();
	}
});


function codeSuggest(){
	var lang=''	
	var editor = vscode.window.activeTextEditor;
	var filename = editor.document.fileName;
	var file_extension = filename.split('.').pop()
	if (!editor) {
		return;
	}
	if (file_extension == 'py' || file_extension == 'ipynb') {
		lang='python'
	}
	else if(file_extension == 'sql') {
		lang='sql'
	}
	else {
		lang='unsupported'
		vscode.window.showErrorMessage('Enterprise AI Code Companion is not supported for ' + file_extension);
	}

	if(lang!='unsupported'){
		vscode.window.showInformationMessage('Enterprise AI Code Companion is generating the optimized code for you');
		const selection = editor.selection;

		var text = editor.document.getText(selection);
		if (text==''){
			var text = editor.document.getText();
		}

		if (text!='') {
			var url='https://anzpathfinders.pythonanywhere.com?lang=' + lang + '&hint= ' + text
			axios.get(url).then(resp => {
				let response_data=resp.data
				response_data = response_data.replace('# Code generated by ANZ Enterprise AI Code Companion', '')
				response_data = response_data.replace('-- Script generated by ANZ Enterprise AI Code Companion', '')
				editor.edit(editBuilder => {
					if(file_extension != 'ipynb'){
					editBuilder.delete(selection)
					editBuilder.insert(editor.selection.active, text);
					}
				});
				codeComplete(editor, response_data)	
				setTimeout(() => {
					codeCleaning();
				}, 1000);
			});
		}
		else{
			vscode.window.showWarningMessage('Please select the input to generate the code completion')
		}
	}
}

function codeComplete(editor, text) {
    let index = 0;
	let words = text.split(' ');
    const intervalId = setInterval(() => {
        editor.edit((editBuilder) => {
			if(index == words.length-1){
				editBuilder.insert(editor.selection.active, words[index] + '');
			}
			else{
            	editBuilder.insert(editor.selection.active, words[index] + ' ');
			}
        });
        index++;
        if (index >= words.length) {
            clearInterval(intervalId);
        }
    }, 50);
	
}

function codeCleaning(){
	let editor = vscode.window.activeTextEditor;

    if (editor) {
      let text = editor.document.getText();

      let lines = text.split('\n');
	  
	  let uniqueLines = Array.from(new Set(lines));
     
	  let updatedLines = []
	  let i=0;
	  uniqueLines.forEach(element => {
		if(element.includes("'''")){
			updatedLines[i]='\n' + element;
		}
		else{
			updatedLines[i]=element;
		}
		i++;
	  });

      let updatedText = updatedLines.join('\n');
 
      let fullRange = new vscode.Range(new vscode.Position(0, 0), editor.document.positionAt(text.length));
      let edit = new vscode.TextEdit(fullRange, updatedText);
      let workspaceEdit = new vscode.WorkspaceEdit();
      workspaceEdit.set(editor.document.uri, [edit]);

      vscode.workspace.applyEdit(workspaceEdit).then(() => {
      });
	}
}

function onTextEditorSelectionChanged(event) {
    const selection = event.textEditor.selection;

    if (selection.isEmpty) {
        console.log('No text selected.');
    } else {
        const selectedText = event.textEditor.document.getText(selection);
		let editor = vscode.window.activeTextEditor;
		//showCompletionItems(editor, selectedText);
    }
}

function showCompletionItems(editor, suggestions) {
	  var completionItems=[]
	  const item = new vscode.CompletionItem(suggestions);
	  item.kind = vscode.CompletionItemKind.Text;
	  completionItems[0]=item

	  item.command = {
		title: 'Generate Code using Enterprise AI Code Companion',
		command: 'extension.codeSuggest'
	};

	//const position = editor.selection.start;
	const completionList = new vscode.CompletionList(completionItems);
	vscode.languages.registerCompletionItemProvider('*', {
	  provideCompletionItems() {
		return completionList;
	  },
	  resolveCompletionItem(item) {
		return item;
	  }
	}, '.', '"', "'", '`', '/', '@');
  
	vscode.commands.executeCommand('editor.action.triggerSuggest');
  }

function activate(context) {
	console.log('Extension "enterprise-code-extension" is running!');
	let disposable1 = vscode.commands.registerCommand('enterprise-code-extension.enterprise-code-companion', function () {
		vscode.window.showInformationMessage('Enterprise AI Code Companion is running...');
	});

	let disposable2 = vscode.commands.registerCommand('enterprise-code-extension.removeDuplicateLines', () => {
		codeCleaning();
	  });

	const pythonProvider = vscode.languages.registerHoverProvider({ scheme: 'file', language: 'python' }, {
        provideHover() {
			const linkText = 'Generate Code using Enterprise AI Code Companion';
			const linkUrl = 'command:extension.codeSuggest';
			const markdownString = new vscode.MarkdownString(`[${linkText}](${linkUrl})`);
			markdownString.isTrusted = true;
			return new vscode.Hover(markdownString);
        }
    });

	const sqlProvider = vscode.languages.registerHoverProvider({ scheme: 'file', language: 'sql' }, {
        provideHover() {
			const linkText = 'Generate script using Enterprise AI Code Companion';
			const linkUrl = 'command:extension.codeSuggest';
			const markdownString = new vscode.MarkdownString(`[${linkText}](${linkUrl})`);
			markdownString.isTrusted = true;
			return new vscode.Hover(markdownString);
        }
    });

	//vscode.window.onDidChangeTextEditorSelection(onTextEditorSelectionChanged);
	context.subscriptions.push(pythonProvider);
	context.subscriptions.push(sqlProvider);
	context.subscriptions.push(vscode.commands.registerCommand('extension.codeSuggest', codeSuggest));
	context.subscriptions.push(disposable1);
	context.subscriptions.push(disposable2);
}

function deactivate() {}

module.exports = {
	activate,
	deactivate
}
